### ISSUE TITLE
upgrade to vite 3.x?

### ISSUE THREAD

**Issue by mesqueeb** [Luncode/vite-vue2-ts-template-starter#1]
i'd love to see this updated to vite 3.x.
it's one of the smaller simpler templates, that's why it's awesome.

**Comment by Luncode** [comment]
> i'd love to see this updated to vite 3.x.
> it's one of the smaller simpler templates, that's why it's awesome.

OK，I can try it

**Comment by Luncode** [comment]
Upgraded vite 4.x
